# Stage 1 — get envsubst binary
FROM alpine:latest AS builder
RUN apk add --no-cache gettext

# Stage 2 — Prometheus base
FROM prom/prometheus:latest

USER root

# Copy envsubst binary from builder
COPY --from=builder /usr/bin/envsubst /usr/local/bin/envsubst

# Copy Prometheus config
COPY prometheus.yaml /etc/prometheus/prometheus.yaml

# Replace env vars and start Prometheus
CMD ["/bin/sh", "-c", "envsubst < /etc/prometheus/prometheus.yaml > /tmp/prometheus.yaml && exec prometheus --config.file=/tmp/prometheus.yaml --web.enable-lifecycle --storage.tsdb.path=/prometheus"]
